all:
	cp ./src/Graph.pm ./
	ln -s ./src/information.pl ./information
	ln -s ./src/fusion.pl ./fusion
	ln -s ./src/chemistry.pl ./chemistry
	chmod 755 ./information
	chmod 755 ./fusion
	chmod 755 ./chemistry

clean:
	rm -f ./Graph.pm
	rm -f ./information
	rm -f ./fusion
	rm -f ./chemistry
